#!/usr/bin/env bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DB_ADMIN_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $DB_ADMIN_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO $DB_ADMIN_USER;
    CREATE USER $DB_PUBLIC_USERNAME WITH PASSWORD '$DB_PUBLIC_PASSWORD';
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO $DB_PUBLIC_USERNAME;
    GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO $DB_PUBLIC_USERNAME;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $DB_PUBLIC_USERNAME;
EOSQL
